import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {GameProvider} from '../context/gameContext';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Whack a mole',
  description: 'Generated by create next app',
  icons: [
    {
      url: '/favicon.png',
      sizes: '32x32',
      type: 'image/png',
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GameProvider>{children}</GameProvider>
      </body>
    </html>
  );
}
